trigger:
- master

jobs:
  - job: 'Win32'
    pool: 
      vmImage: 'vs2017-win2016'
    steps:
      - checkout: self
        submodules: true
      
      - task: CMake@1
        inputs:
          cmakeArgs: >
            -G"Visual Studio 15 2017"
            -A"Win32"
            -DCMAKE_INSTALL_PREFIX=$(Build.ArtifactStagingDirectory)
            $(Build.SourcesDirectory)
      
      - task: CMake@1
        inputs:
          cmakeArgs: >
            --build ./
            --config Release
            --target install
      
      - script: ctest -C Release
        workingDirectory: build
        displayName: Test

      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: $(Build.ArtifactStagingDirectory)
          artifactName: 'Win32'
